Pgsql
datagrok-ai/ansible-role-datagrok-monitoring pull request #3
Opened 2023-01-04 14:08 UTC by ksumag

add pqsql exporter  container launch with scrape metrics config for Prometheus

2023-01-04 14:18 UTC, dnillovna requested changes

2023-01-04 14:18 UTC, dnillovna commented on tasks/postgres.yml
> +  tags: ['pg_exporter']
```suggestion
  tags: ['pg_exporter']

```

2023-01-04 14:18 UTC, dnillovna commented on tasks/postgres.yml
> +      {{ monitoring_pgsql_parameters }}
```suggestion
    env: {{ monitoring_pgsql_parameters | default ({}) }}
```

2023-01-04 14:18 UTC, dnillovna commented on tasks/postgres.yml
> +      - name: "{{ monitoring_docker_network_name }}"
What is the default value for the variable?

2023-01-04 14:18 UTC, dnillovna commented on templates/prometheus.yml.j2
> +{% endif %}
```suggestion
{% endif %}

```

2023-01-04 14:18 UTC, dnillovna commented on templates/prometheus.yml.j2
> +      - targets: ['{{monitoring_pgsql_db_host}}:{{monitoring_pgsql_exporter_port}}']
```suggestion
      - targets: ['{{ monitoring_pgsql_db_host }}:{{ monitoring_pgsql_exporter_port }}']
```
do not forget to run linter)

2023-01-04 14:18 UTC, dnillovna commented on templates/prometheus.yml.j2
> +          hostname: {{monitoring_pgsql_db_host}}
```suggestion
          hostname: {{ monitoring_pgsql_db_host }}
```

2023-01-04 14:26 UTC, ksumag commented on tasks/postgres.yml
> +      - name: "{{ monitoring_docker_network_name }}"
monitoring, https://github.com/datagrok-ai/ansible-role-datagrok-monitoring/blob/pgsql/defaults/main.yml#L7

2023-01-04 14:47 UTC, ksumag commented on tasks/postgres.yml
> +      {{ monitoring_pgsql_parameters }}
env: "{{ monitoring_pgsql_parameters | default ({}) }}"

2023-01-05 12:56 UTC, dnillovna requested changes

2023-01-05 12:56 UTC, dnillovna commented on defaults/main.yml
> +monitoring_postgresql_enabled: true
```suggestion
monitoring_pgsql_exporter_enabled: true
```
The names of the variables should be consistent. Check all the variables and make sure that they have similar prefixes, for example `monitoring_pgsql_exporter_`

2023-01-05 12:56 UTC, dnillovna commented on tasks/main.yml
> +    - monitoring_targets_inventory_group in group_names
```suggestion
  delegate_to: "{{ monitoring_pgsql_db_host }}"
  run_once: true
```

2023-01-05 12:56 UTC, dnillovna commented on tasks/postgres.yml
> +  delegate_to: "{{ monitoring_pgsql_db_host }}"
```suggestion
```

2023-01-05 16:12 UTC, ksumag commented on templates/prometheus.yml.j2
> +      - targets: ['{{ hostvars[monitoring_pgsql_db_host]["ansible_host"] }}:{{ monitoring_pgsql_exporter_port }}']
don't understand link on the same PR, I've got one target to scrape, what's wrong?

2023-01-05 16:58 UTC, dnillovna commented on templates/prometheus.yml.j2
> +      - targets: ['{{ hostvars[monitoring_pgsql_db_host]["ansible_host"] }}:{{ monitoring_pgsql_exporter_port }}']
```
      - targets: [
        {%- if host == inventory_hostname -%}
          'cadvisor:{{ monitoring_cadvisor_port }}'
        {%- else -%}
          '{{ hostvars[host]["monitoring_advertise_address"] | default(hostvars[host]["ansible_host"]) }}:{{ monitoring_cadvisor_port }}'
        {%- endif -%}]
```

2023-01-05 17:03 UTC, dnillovna commented on templates/prometheus.yml.j2
> +{% endif %}
```
    relabel_configs:
      - source_labels: [hostname]
        target_label: instance
```

2023-01-24 16:02 UTC, dnillovna requested changes

2023-01-24 16:09 UTC, dnillovna commented on templates/alertmanager.yml.j2
> +    - job="container_metrics"
I should not be enabled by default. Cause some of our clients won't have such container names.
I suggest
```suggestion
{% if monitoring_except_rules | default([]) | length > 0 %}
  routes: 
  {% for rule in monitoring_except_rules %}
  - receiver: "{{ rule.receiver | default('null') }}"
    matchers:
    {% for matcher in  rule.matchers %}
        - {{ matcher }}
    {% endfor %}
{% endfor %}
```

2023-02-01 18:30 UTC, dnillovna requested changes

2023-02-01 18:30 UTC, dnillovna commented on templates/alert_rules.yml.j2
> +        summary: "{{ $labels.instance }}: Container {{ $labels.name }} CPU usage > 90%"
```suggestion
        summary: "{{ $labels.instance }}: {{ $labels.name }} container CPU usage > 90%"
```

2023-02-01 18:30 UTC, dnillovna commented on templates/alert_rules.yml.j2
> +        summary: "{{ $labels.instance }}: Container {{ $labels.name }} Memory usage > 85%"
```suggestion
        summary: "{{ $labels.instance }}: {{ $labels.name }} container Memory usage > 85%"
```

2023-02-01 18:30 UTC, dnillovna commented on templates/alert_rules.yml.j2
> +        summary: "{{ $labels.instance }}: Container {{ $labels.name }} high throttle rate"
```suggestion
        summary: "{{ $labels.instance }}: {{ $labels.name }} container high throttle rate"
```

2023-02-01 18:30 UTC, dnillovna commented on templates/alert_rules.yml.j2
> +        summary: "Blackbox probe failed on {{ $labels.instance }}"
```suggestion
        summary: "{{ $labels.instance }}: Blackbox probe failed"
```

2023-02-02 08:34 UTC, dnillovna commented on templates/alert_rules.yml.j2
> +        summary: "{{ $value }} HTTP code on {{ $labels.instance }}"
```suggestion
        summary: "{{ $labels.instance }}: {{ $value }} HTTP code"
```

2023-02-02 08:38 UTC, merged